"""Add Storage table for isolated file access

Revision ID: 20220114_103500_storage_table
Revises: 20211211_002700_add_upload_ip
Create Date: 2022-01-14 11:58:22.140682

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20220114_103500_storage_table"
down_revision = "20211211_002700_add_upload_ip"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("storage")
    # ### end Alembic commands ###
