# CrashServer Configuration File

[flask]
secret_key = "changeme"

[postgres]
hostname = ""
username = ""
password = ""
database = ""

[storage]
minidump_location = "data/minidumps"
symbol_location = "data/symbols"