# CrashServer Configuration File

[default]
    [default.flask]
    # Set to a cryptographic random string
    secret_key  = "changeme"
    domain      = "https://example.com"
    web_port    = 8888

    # Currently, only postgres is supported
    [default.db]
    user    = "postgres"
    passwd  = "password"
    host    = "localhost"
    port    = 5432
    name    = "crashserver"

    # Local storage directories
    # Symbols are what make CrashServer work! Keep them safe.
    # Minidumps are ephemeral, once decoded, they are not needed anymore.
    # Sym Upload is for the `sym-upload-v2` protocol. It's used as a staging directory
    # before the file is added to the database or deleted.
    [default.storage]
    appdata     = "/storage"
    logs        = "/logs"
