# CrashServer Configuration File

[default]
SECRET_KEY = "changeme"

    [default.flask]
    web_port    = 8888

    # Currently, only postgres is supported
    [default.db]
    user    = "postgres"
    passwd  = "password"
    host    = "postgres"
    port    = 5432
    name    = "crashserver"

    [default.redis]
    host = "redis"
    port = 6379

    # Docker-based default storage directories
    [default.storage]
    appdata     = "/storage"
    logs        = "/logs"

[testing]
WTF_CSRF_ENABLED = false

    [testing.db]
    name = "test_crashserver"

    [testing.login]
    email = "test@test.com"
    passwd = "password"