# CrashServer Configuration File

[default]
    [default.flask]
    # Set to a cryptographic random string
    secret_key  = "changeme"
    web_port    = 8888

    # Currently, only postgres is supported
    [default.db]
    user    = "postgres"
    passwd  = "password"
    host    = "localhost"
    port    = 5432
    name    = "crashserver"

    # Local storage directories
    [default.storage]
    appdata     = "data/appdata"
    logs        = "data/logs"

[docker]
    [docker.storage]
    appdata     = "/storage"
    logs        = "/logs"
