# CrashServer Configuration File

[default]
    [default.flask]
    # Set to a cryptographic random string
    secret_key  = "changeme"
    web_port    = 8888

    # Currently, only postgres is supported
    [default.db]
    user    = "postgres"
    passwd  = "password"
    host    = "postgres"
    port    = 5432
    name    = "crashserver"

    [default.redis]
    host = "redis"
    port = 6379

    # Docker-based default storage directories
    [default.storage]
    appdata     = "/storage"
    logs        = "/logs"
