# Development docker-compose.yml
# Run `docker-compose up -d` in the directory, and the following things will happen
# 1. A postgres and redis container will be created. These are required backend services.
# 2. Two containers will be created based on the `Dockerfile.dev` in the root of the project.
#    This dockerfile allow the source code in the root of the project to be used with the rest
#    of the docker environment. You can modify the source, and since the flask development
#    server is used, the changes will be updated immediately.
# 3. A folder called `data` will be created in this directory. All appdata and log output
#    will be stored within this directory

version: "3.0"

networks:
    crashnet:
        driver: bridge

services:
    redis:
        image: redis:6.2.5
        container_name: redis
        networks: [crashnet]
        ports: ["6379:6379"]

    postgres:
        image: postgres
        container_name: postgres
        networks: [crashnet]
        volumes: [db_data:/var/lib/postgresql/data]
        ports: ["5432:5432"]
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-crashserver}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}


    crashserver-app:
        build:
            context: ..
            dockerfile: Dockerfile.dev
        container_name: crashserver-app
        networks: [crashnet]
        depends_on: [postgres, crashserver-worker]
        ports: ["8888:8888"]
        volumes:
            - ../:/app/

            # App Data
            - ./logs:/logs
            - ./storage:/storage
        environment:
            FLASK_APP: crashserver/webapp:create_app
            FLASK_RUN_HOST: 0.0.0.0
            FLASK_RUN_PORT: 8888
            FLASK_DEBUG: 1
            CRASH_DB__DB: ${POSTGRES_DB:-crashserver}
            CRASH_DB__USER: ${POSTGRES_USER:-postgres}
            CRASH_DB__PASSWD: ${POSTGRES_PASSWORD:-password}
            CRASH_DB__HOST: ${CRASH_DB__HOST:-postgres}
            CRASH_S3STORE__BUCKET_NAME: ${CRASH_S3STORE__BUCKET_NAME:-crashserver}
            CRASH_S3STORE__ACCESS_KEY: ${CRASH_S3STORE__ACCESS_KEY}
            CRASH_S3STORE__SECRET_KEY: ${CRASH_S3STORE__SECRET_KEY}
            CRASH_S3STORE__ENDPOINT_URL: ${CRASH_S3STORE__ENDPOINT_URL:-"https://s3.amasonaws.com"}
            TZ: ${TZ:-UTC}

    crashserver-worker:
        container_name: crashserver-worker
        build:
            context: ..
            dockerfile: Dockerfile.dev
        command: rq worker -u redis://redis crashserver
        depends_on: [redis]
        networks: [crashnet]
        volumes: ["./storage:/storage", "../:/app/"]
        environment:
            CRASH_DB__DB: ${POSTGRES_DB:-crashserver}
            CRASH_DB__USER: ${POSTGRES_USER:-postgres}
            CRASH_DB__PASSWD: ${POSTGRES_PASSWORD:-password}
            CRASH_DB__HOST: ${CRASH_DB__HOST:-postgres}


volumes:
    db_data: