name: Docker Container Build
on: push

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CrashServer
        uses: actions/checkout@v2

      - name: Build App Image
        run: docker build -t jameskr97/crashserver:dev . 
