name: Github Container Upload
on:
  release:
    types: [published]

jobs:
    ghcr:
      name: Upload to Github Container Registry
      runs-on: ubuntu-latest
      steps:
        - name: Checkout CrashServer
          uses: actions/checkout@v2

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GHCR_TOKEN }}

        - name: Generate Container Metadata
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: ghcr.io/jameskr97/crashserver
            tags: |
              type=ref,event=tag
              type=semver,pattern={{major}}.{{minor}}.{{patch}}
              type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

        - name: Build and push
          id: build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
