name: Code Linting
on: push

jobs:
  lint-with-blackd:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CrashServer
        uses: actions/checkout@v2

      - name: Run Black Formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"